"""Computational models for the Evolution-Creation project."""

from .assortment import (
    EndogamySpreadResult,
    deterministic_endogamy_curve,
    make_endogamy_matrix,
    probability_all_communities_reached,
    simulate_endogamy_founder_spread,
    simulate_endogamy_replicates,
)
from .demography import (
    DemographicSpreadResult,
    OverlapSpreadResult,
    apply_population_bottleneck,
    constant_population_schedule,
    deterministic_ancestry_fraction_curve,
    deterministic_descendant_counts,
    deterministic_overlapping_ancestry_fractions,
    exponential_population_schedule,
    logistic_population_schedule,
    simulate_demographic_founder_spread,
    simulate_demographic_replicates,
    simulate_overlapping_ancestry_sets,
)
from .genealogy import FounderSpreadResult, simulate_founder_spread, simulate_replicates
from .structured import (
    StructuredSpreadResult,
    add_linear_barrier,
    make_linear_migration_matrix,
    probability_of_global_fixation,
    simulate_structured_founder_spread,
    simulate_structured_replicates,
)
from .temporal import (
    TemporalSpreadResult,
    make_barrier_schedule,
    make_constant_schedule,
    probability_of_global_fixation_by_barrier_timing,
    simulate_time_varying_founder_spread,
    simulate_time_varying_replicates,
)

__all__ = [
    "DemographicSpreadResult",
    "EndogamySpreadResult",
    "FounderSpreadResult",
    "OverlapSpreadResult",
    "StructuredSpreadResult",
    "TemporalSpreadResult",
    "add_linear_barrier",
    "apply_population_bottleneck",
    "constant_population_schedule",
    "deterministic_ancestry_fraction_curve",
    "deterministic_descendant_counts",
    "deterministic_endogamy_curve",
    "deterministic_overlapping_ancestry_fractions",
    "exponential_population_schedule",
    "logistic_population_schedule",
    "make_barrier_schedule",
    "make_constant_schedule",
    "make_endogamy_matrix",
    "make_linear_migration_matrix",
    "probability_all_communities_reached",
    "probability_of_global_fixation",
    "probability_of_global_fixation_by_barrier_timing",
    "simulate_demographic_founder_spread",
    "simulate_demographic_replicates",
    "simulate_endogamy_founder_spread",
    "simulate_endogamy_replicates",
    "simulate_founder_spread",
    "simulate_overlapping_ancestry_sets",
    "simulate_replicates",
    "simulate_structured_founder_spread",
    "simulate_structured_replicates",
    "simulate_time_varying_founder_spread",
    "simulate_time_varying_replicates",
]
